
name: Deploy to ECS

on:
  push:
    branches: [ "prod" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::575327645493:role/crud-api-ecs
          aws-region: us-east-1

      - name: Login to ECR
        run: aws ecr get-login-password --region us-east-1 |
          docker login --username AWS --password-stdin 575327645493.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t crud-api:latest .

      - name: Push image to ECR
        run: |
          docker tag crud-api:latest 575327645493.dkr.ecr.us-east-1.amazonaws.com/crud-api:latest
          docker push 575327645493.dkr.ecr.us-east-1.amazonaws.com/crud-api:latest

      - name: Create task definition JSON dynamically
        run: |
          cat > task-def.json <<EOF
          {
            "family": "crud-api",
            "networkMode": "awsvpc",
            "requiresCompatibilities": [ "FARGATE" ],
            "cpu": "256",
            "memory": "512",
            "executionRoleArn": "<TASK_EXECUTION_ROLE_ARN>",
            "containerDefinitions": [
              {
                "name": "crud-api",
                "image": "575327645493.dkr.ecr.us-east-1.amazonaws.com/crud-api:latest",
                "portMappings": [
                  {
                    "containerPort": 5000,
                    "protocol": "tcp"
                  }
                ],
                "essential": true
              }
            ]
          }
          EOF

      - name: Register task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://task-def.json

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster crud-api \
            --service crud-service \
            --force-new-deployment

      
      
    
