name: Deploy CRUD API to ECS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: crud-api
  ECS_CLUSTER: crud-api
  ECS_SERVICE: crud-service
  ECS_TASK_DEFINITION: crud-api-task.json
  CONTAINER_NAME: crud-container

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::575327645493:role/crud-api-ecs

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag & Push image
        id: build-image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          ECR_URI=${{ steps.ecr-login.outputs.registry }}
          docker build -t $ECR_URI/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_URI/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_URI/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Render new task definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
